spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/f_produits
    username: masseta
    password: admin
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10


logging:
  level:
    '[org.springframework.security]': debug

appli:
  secretKey: trololol
  validity: 36000
  rememberMe: 0